[main]
# Configuración de la fuente
font=JetBrainsMono Nerd Font:size=13
include=~/.cache/wal/colors-foot.ini

[colors]
alpha=0.5

[csd]
# Opcional: Ocultar la barra de título si prefieres un look minimalista
size=0
